### ISSUE TITLE
在项目中调用MRCarUtil.plateRecognition方法出错

### ISSUE THREAD

**Issue by Gemini701** [imistyrain/EasyPR4Android#10]
你好，在测试项目中尝试调用MRCarUtil.plateRecognition（）后出现以下提示：
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String ×××.modData.MRCarUtil.plateRecognition(long, long) (tried ×××.modData_MRCarUtil_plateRecognition and ×××.modData_MRCarUtil_plateRecognition__JJ)
at ×××.modData.MRCarUtil.plateRecognition(Native Method)

请问需要如何配置呢？谢谢！

**Comment by imistyrain** [comment]
自己建的项目需要拷贝编译好的so库到libs下

**Comment by Gemini701** [comment]
嗯谢谢，已经解决了 ;)
