### ISSUE TITLE
make project时出现undefined reference to错误

### ISSUE THREAD

**Issue by krizalid9999** [imistyrain/EasyPR4Android#13]
AndroidStudio3.4.2 NDK20.0 已安装Ninja
makeProject时报错，是否是NDK版本或其他出了问题？
`CMakeFiles/mrcar.dir/src/main/jni/src/core/core_func.cpp.o: In function `easypr::showResult(cv::Mat const&, int)':
E:\Demo\EasyPR4Android-master2\EasyPR4Android-master\app\.externalNativeBuild\cmake\debug\arm64-v8a/../../../../src/main/jni/src/core/core_func.cpp:2473: undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__ndk1::vector<int, std::__ndk1::allocator<int> > const&)'
CMakeFiles/mrcar.dir/src/main/jni/src/core/core_func.cpp.o: In function `easypr::writeTempImage(cv::Mat const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, int)':
E:\Demo\EasyPR4Android-master2\EasyPR4Android-master\app\.externalNativeBuild\cmake\debug\arm64-v8a/../../../../src/main/jni/src/core/core_func.cpp:2567: undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__ndk1::vector<int, std::__ndk1::allocator<int> > const&)'
CMakeFiles/mrcar.dir/src/main/jni/src/core/feature.cpp.o: In function `easypr::getHOGFeatures(cv::Mat const&, cv::Mat&)':
E:\Demo\EasyPR4Android-master2\EasyPR4Android-master\app\.externalNativeBuild\cmake\debug\arm64-v8a/../../../../src/main/jni/src/core/feature.cpp:120: undefined reference to `cv::HOGDescriptor::compute(cv::_InputArray const&, std::__ndk1::vector<float, std::__ndk1::allocator<float> >&, cv::Size_<int>, cv::Size_<int>, std::__ndk1::vector<cv::Point_<int>, std::__ndk1::allocator<cv::Point_<int> > > const&) const'
CMakeFiles/mrcar.dir/src/main/jni/src/train/ann_train.cpp.o: In function `easypr::AnnTrain::sdata(unsigned long)':
E:\Demo\EasyPR4Android-master2\EasyPR4Android-master\app\.externalNativeBuild\cmake\debug\arm64-v8a/../../../../src/main/jni/src/train/ann_train.cpp:287: undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__ndk1::vector<int, std::__ndk1::allocator<int> > const&)'
CMakeFiles/mrcar.dir/src/main/jni/src/util/util.cpp.o: In function `easypr::Utils::imwrite(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, cv::Mat const&)':
E:\Demo\EasyPR4Android-master2\EasyPR4Android-master\app\.externalNativeBuild\cmake\debug\arm64-v8a/../../../../src/main/jni/src/util/util.cpp:250: undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__ndk1::vector<int, std::__ndk1::allocator<int> > const&)'
CMakeFiles/mrcar.dir/src/main/jni/thirdparty/textDetect/erfilter.cpp.o: In function `cv::text::MaxMeaningfulClustering::probability(std::__ndk1::vector<int, std::__ndk1::allocator<int> >&)':
E:\Demo\EasyPR4Android-master2\EasyPR4Android-master\app\.externalNativeBuild\cmake\debug\arm64-v8a/../../../../src/main/jni/thirdparty/textDetect/erfilter.cpp:2647: undefined reference to `cv::Subdiv2D::getEdgeList(std::__ndk1::vector<cv::Vec<float, 4>, std::__ndk1::allocator<cv::Vec<float, 4> > >&) const'
CMakeFiles/mrcar.dir/src/main/jni/thirdparty/textDetect/erfilter.cpp.o: In function `cv::text::erGroupingNM(cv::_InputArray const&, cv::_InputArray const&, std::__ndk1::vector<std::__ndk1::vector<cv::text::ERStat, std::__ndk1::allocator<cv::text::ERStat> >, std::__ndk1::allocator<std::__ndk1::vector<cv::text::ERStat, std::__ndk1::allocator<cv::text::ERStat> > > >&, std::__ndk1::vector<std::__ndk1::vector<cv::Vec<int, 2>, std::__ndk1::allocator<cv::Vec<int, 2> > >, std::__ndk1::allocator<std::__ndk1::vector<cv::Vec<int, 2>, std::__ndk1::allocator<cv::Vec<int, 2> > > > >&, std::__ndk1::vector<cv::Rect_<int>, std::__ndk1::allocator<cv::Rect_<int> > >&, bool)':
E:\Demo\EasyPR4Android-master2\EasyPR4Android-master\app\.externalNativeBuild\cmake\debug\arm64-v8a/../../../../src/main/jni/thirdparty/textDetect/erfilter.cpp:3774: undefined reference to `cv::_InputArray::getMatVector(std::__ndk1::vector<cv::Mat, std::__ndk1::allocator<cv::Mat> >&) const'
CMakeFiles/mrcar.dir/src/main/jni/thirdparty/textDetect/erfilter.cpp.o: In function `cv::text::erGroupingGK(cv::_InputArray const&, cv::_InputArray const&, std::__ndk1::vector<std::__ndk1::vector<cv::text::ERStat, std::__ndk1::allocator<cv::text::ERStat> >, std::__ndk1::allocator<std::__ndk1::vector<cv::text::ERStat, std::__ndk1::allocator<cv::text::ERStat> > > >&, std::__ndk1::vector<std::__ndk1::vector<cv::Vec<int, 2>, std::__ndk1::allocator<cv::Vec<int, 2> > >, std::__ndk1::allocator<std::__ndk1::vector<cv::Vec<int, 2>, std::__ndk1::allocator<cv::Vec<int, 2> > > > >&, std::__ndk1::vector<cv::Rect_<int>, std::__ndk1::allocator<cv::Rect_<int> > >&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, float)':
E:\Demo\EasyPR4Android-master2\EasyPR4Android-master\app\.externalNativeBuild\cmake\debug\arm64-v8a/../../../../src/main/jni/thirdparty/textDetect/erfilter.cpp:3045: undefined reference to `cv::_InputArray::getMatVector(std::__ndk1::vector<cv::Mat, std::__ndk1::allocator<cv::Mat> >&) const'
`

**Comment by imistyrain** [comment]
我用的ndk版本是16，可能是他们的兼容性不好
