### ISSUE TITLE
无法编译，可否出一下导入编译流程？

### ISSUE THREAD

**Issue by persistGithub** [imistyrain/EasyPR4Android#16]
Android Studio 4的版本

**Comment by persistGithub** [comment]
NDK使用的r16b

**Comment by persistGithub** [comment]
NDK使用的r16b
但是在Build的时候,会报错误
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

**Comment by persistGithub** [comment]
NDK使用的r16b
但是在Build的时候,会报错误
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

**Comment by imistyrain** [comment]
将工程的Gradle升级为 3.3.2， buildToolsVersion使用28.0.3
