### ISSUE TITLE
自己编译处理的APK和demo的已经打包好了的APK识别精准度有巨大差异

### ISSUE THREAD

**Issue by persistGithub** [imistyrain/EasyPR4Android#17]
自己编译安装的APK在识别速度\识别精准度上和demo的apk差异很大 自己编译的在中文基本不准，demo的APK就很精准和快速

**Comment by persistGithub** [comment]
编译出来的APK只有13MB，demo的有20MB，麻烦问下有没有办法提高精度呢？

**Comment by imistyrain** [comment]
开源的只是整体的框架，模型还是要加数据自己训练的哦
