### ISSUE TITLE
编译ERROR: A problem occurred configuring project ':app'.

### ISSUE THREAD

**Issue by qiulongquan** [imistyrain/EasyPR4Android#19]
build的时候出现下面的错误，无法正常编译，有人知道如何解决吗？
环境：Android Studio 3.5.2 
           Android Gradle plugin version 3.11
          Gradle version 4.4
          NDK  23.1.7779620
          android SDK版本为28
         Build Tools version 28.0.3

Gradle sync issues
         A problem occurred configuring project ':app'.

google查了一下，好像说Android Studio 升级版本后，对于命名有了新的要求，所以build的时候出现error。

**Comment by imistyrain** [comment]
可能是NDK版本太高了吧，换成16.1试下
