### ISSUE TITLE
error when OpenCV_DIR was not set correctly

### ISSUE THREAD

**Issue by 2573703932** [imistyrain/EasyPR4Android#4]
![image](https://user-images.githubusercontent.com/24774100/31179099-8c2d3fd6-a94d-11e7-9739-5f540afcc684.png)

**Comment by cswangduo** [comment]
修改set(OpenCV_DIR ../../../)这行代码为你本地 OpenCV 的目录
比如我修改为：set(OpenCV_DIR /Users/wangduo/Library/OpenCV-android-sdk/sdk/native/jni)
