### ISSUE TITLE
您确定是ndk r12d版本吗

### ISSUE THREAD

**Issue by NikiLee2016** [imistyrain/EasyPR4Android#6]
我看了下ndk的下载列表, 只有ndk r12b, 没有看到ndk r12d, 然后现在项目导入之后编译通不过(用的ndk r12b), 不知道是不是这个问题引起的,
报错如下:
External Native Build Issues
Build command failed.
Error while executing 'D:\ADT\sdk\cmake\3.6.3155560\bin\cmake.exe' with arguments {-HF:\Android_Studio\002_Night_Theme01\EasyPhoto -BF:\Android_Studio\002_Night_Theme01\EasyPhoto\.externalNativeBuild\cmake\debug\arm64-v8a -GAndroid Gradle - Ninja -DANDROID_ABI=arm64-v8a -DANDROID_NDK=D:\ADT\sdk\ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=F:\Android_Studio\002_Night_Theme01\EasyPhoto\build\intermediates\cmake\debug\obj\arm64-v8a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=D:\ADT\sdk\cmake\3.6.3155560\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=D:\ADT\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=21 -DCMAKE_CXX_FLAGS=-std=c++11}
-- Check for working C compiler: D:/ADT/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: D:/ADT/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/ADT/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: D:/ADT/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "F:/Android_Studio/002_Night_Theme01/EasyPhoto/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeOutput.log".
CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:
    OpenCVConfig.cmake
    opencv-config.cmake
  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.
Build command failed.
Error while executing 'D:\ADT\sdk\cmake\3.6.3155560\bin\cmake.exe' with arguments {-HF:\Android_Studio\002_Night_Theme01\EasyPhoto -BF:\Android_Studio\002_Night_Theme01\EasyPhoto\.externalNativeBuild\cmake\release\arm64-v8a -GAndroid Gradle - Ninja -DANDROID_ABI=arm64-v8a -DANDROID_NDK=D:\ADT\sdk\ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=F:\Android_Studio\002_Night_Theme01\EasyPhoto\build\intermediates\cmake\release\obj\arm64-v8a -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=D:\ADT\sdk\cmake\3.6.3155560\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=D:\ADT\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=21 -DCMAKE_CXX_FLAGS=-std=c++11}
-- Check for working C compiler: D:/ADT/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: D:/ADT/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/ADT/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: D:/ADT/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "F:/Android_Studio/002_Night_Theme01/EasyPhoto/.externalNativeBuild/cmake/release/arm64-v8a/CMakeFiles/CMakeOutput.log".
CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:
    OpenCVConfig.cmake
    opencv-config.cmake
  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by imistyrain** [comment]
提示是没找到opencv,你得把OPENCV_DIR那的相对路径设置正确才行
